//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Orders {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Orders.IOrders")]
    public interface IOrders {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetPrice", ReplyAction="http://tempuri.org/IOrders/GetPriceResponse")]
        decimal GetPrice(string code, decimal quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/GetPrice", ReplyAction="http://tempuri.org/IOrders/GetPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetPriceAsync(string code, decimal quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersChannel : Client.Orders.IOrders, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersClient : System.ServiceModel.ClientBase<Client.Orders.IOrders>, Client.Orders.IOrders {
        
        public OrdersClient() {
        }
        
        public OrdersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetPrice(string code, decimal quantity) {
            return base.Channel.GetPrice(code, quantity);
        }
        
        public System.Threading.Tasks.Task<decimal> GetPriceAsync(string code, decimal quantity) {
            return base.Channel.GetPriceAsync(code, quantity);
        }
    }
}
